#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

use Illuminate\Contracts\Console\Kernel;
use Symfony\Component\Console\Input\StringInput;
use Symfony\Component\Console\Output\BufferedOutput;

function handle_queue($event) {

    $app = require __DIR__.'/bootstrap/app.php';

    $commandOptions = trim(sprintf(
        '--delay=%s --tries=%s %s',
        $_ENV['SQS_DELAY'] ?? 3,
        $_ENV['SQS_TRIES'] ?? 3,
        ($_ENV['SQS_FORCE'] ?? false) ? '--force' : ''
    ));

    $consoleKernel = $app->make(Kernel::class);

    $consoleInput = new StringInput(
        'vapor:work '.base64_encode(json_encode($event['Records'][0])).' '.$commandOptions.' --no-interaction'
    );

    $consoleKernel->terminate($consoleInput, $status = $consoleKernel->handle(
        $consoleInput, $output = new BufferedOutput
    ));

    return [
        'statusCode' => $status,
        'output' => base64_encode($output->fetch()),
    ];
}

lambda(function ($event) {
    return handle_queue($event);
});
