#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

use Illuminate\Contracts\Console\Kernel;
use Symfony\Component\Console\Input\StringInput;
use Symfony\Component\Console\Output\BufferedOutput;

function handle_schedule($event) {

    $app = require __DIR__.'/bootstrap/app.php';

    $consoleKernel = $app->make(Kernel::class);

    $consoleInput = new StringInput(
        'sync:all-github-recently-mentionable-users'
    );

    $consoleKernel->terminate($consoleInput, $status = $consoleKernel->handle(
        $consoleInput, $output = new BufferedOutput
    ));

    return [
        'statusCode' => $status,
        'output' => base64_encode($output->fetch()),
    ];
}

lambda(function ($event) {
    return handle_schedule($event);
});
